### ISSUE TITLE
Feature Request: Raw API Mode

### ISSUE THREAD

**Issue by ushuz** [ucloud/ucloud-cli#52]
Provide a command to talk to API directly, so users can interact with APIs not yet natively supported without having to handle request signing themselves. ucloud-cli's credential management and request signing functionalities will be appreciated and reused this way.

Proposed:
```
ucloud api Parameter=Value [Parameter=Value] ...
```

Example, to create a UK8S cluster through API
```
ucloud api Action=CreateUK8SClusterV2 ... Master.1.Zone=cn-bj2-02 ... MasterCPU=2 ... 
```

**Comment by lixiaojun629** [comment]
supported in version 0.1.33

**Comment by ushuz** [comment]
@lixiaojun629 Nice work, thank you for your quick resolution.
