### ISSUE TITLE
创建 GlobalSSH 时不能指定 GlobalSSH 端口，也无法使用 ucloud gssh list 命令查看

### ISSUE THREAD

**Issue by franklee095** [ucloud/ucloud-cli#56]
故障示例：

执行 ucloud gssh create --location Washington --target-ip 152.32.140.92 可以正常创建 GlobalSSH 通道，

但执行 ucloud gssh create --location Washington --target-ip 152.32.140.99 --port 2345 会报错 RetCode:33760

且执行 ucloud gssh list 命令并不能显示已创建的 GlobalSSH 服务器端口，只能从 ucloud 网站查看。

建议：

如果在创建 GlobalSSH 通道时必须保留现有的随机分配端口机制而不能指定 GlobalSSH 服务器端口，那至少在使用 ucloud gssh list 命令查看时要增加这一栏，否则无法连接。

**Comment by shawnmssu** [comment]
首先目前 ucloud cli 仅支持创建免费版的 GlobalSSH，免费版的仅支持配置服务器端口 22 和 3389 ，且会随机 GlobalSSH 端口；故指定端口不为 22 或 3389 时，会报 retcode 错误;

**Comment by root0day** [comment]
![image](https://user-images.githubusercontent.com/26130494/116588625-5c89a580-a94e-11eb-9bc5-9c1b630a0c45.png)
使用
ucloud api --Action DescribeGlobalSSHInstance --InstanceId uga-xxxxxx
这个命令就行了

**Comment by nuannuan0922** [comment]
您好！
我已收到您的邮件，谢谢！
                                                                           霍超群
